### DISCUSSION TITLE
Referencing local EE's within navigator config

### DISCUSSION THREAD

**Discussion by cloin** [ansible/ansible-navigator#574] [Q&A] [answered]
As part of our cloud image build process, we download a few of the supported EE's from Red Hat registry with valid authentication. When an instance is provisioned against that cloud image, and navigator is configured to pull an image with the `latest` tag, navigator will prompt for registry credentials. 
```
---
ansible-navigator:
  execution-environment:
    container-engine: podman
    image: ee-supported-rhel8:latest
    enabled: true

  playbook-artifact:
    save-as: /home/rhel/playbook-artifacts/{playbook_name}-artifact-{ts_utc}.json

  logging:
    level: debug
```

```
[rhel@code-server ~]$ ansible-navigator run ./test.yml
------------------------------------------------------------
Execution environment image and pull policy overview
------------------------------------------------------------
Execution environment image name:  ee-supported-rhel8:latest
Execution environment image tag:   latest
Execution environment pull policy: tag
Execution environment pull needed: True
------------------------------------------------------------
Updating the execution environment
------------------------------------------------------------
✔ registry.redhat.io/ee-supported-rhel8:latest
Trying to pull registry.redhat.io/ee-supported-rhel8:latest...
Error: Error initializing source docker://registry.redhat.io/ee-supported-rhel8:latest: unable to retrieve auth token: invalid username/password: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
[ERROR]: Execution environment pull failed
 [HINT]: Check the execution environment image name, connectivity to and permissions for the registry, and try again
```

**Comment by cloin** [comment, marked as answer]
Replacing `latest` with the proper tag for the EE already present on filesystem (eg: `2.0.0`) seems to be the proper way to use a pre-loaded EE and navigator does not prompt for authentication.

If the EE images have already been pulled during cloud image build process, this configuration works:
```
---
ansible-navigator:
  execution-environment:
    container-engine: podman
    image: ee-supported-rhel8:2.0.0
    enabled: true

  playbook-artifact:
    save-as: /home/rhel/playbook-artifacts/{playbook_name}-artifact-{ts_utc}.json

  logging:
    level: debug
```

Using the properly tagged image on filesystem instead of `latest` produces the expected results. Run `ansible-navigator --ee false images` to view images and their tags.
