### DISCUSSION TITLE
how to pass limit to ansible-navigator run

### DISCUSSION THREAD

**Discussion by DE110283** [ansible/ansible-navigator#834] [Q&A] [answered]
I can't find any information about how to pass a limit for example to a given host or group when executing playbooks using ansible-navigator run.
If this feature is not available I would like to raise a feature request to add a limit argument, like for ansible-playbook:

`ansible-navigator run <playbook> -l <host|group>`

**Comment by cidrblock** [comment]
@DE110283 Thanks for the question...

ansible-navigator should pass through any unrecognized parameters for itself to the underlying call to ansible-playbook.

So it _should_ just "work" :)

It's buried pretty deep in the help, but if you `ansible-navigator run --help``` you'll see this.


```
Note: 'ansible-navigator run' additionally supports the same parameters as the 'ansible-playbook' command. For more information about these, try 'ansible-navigator run --help-playbook --mode stdout'
```

Try it out and let me know, I'm shutting down for the day but can look next week.

thanks again for logging the question and trying it out!

**Comment by cidrblock** [comment, marked as answer]
yeah, this seems to works fine with a quick test.... here's my inventory

```
all:
  vars:
    ansible_user: admin
    ansible_password: password
    ansible_become_pass: password
    ansible_become: True
    ansible_become_method: enable
    ansible_connection: ansible.netcommon.network_cli
    ansible_python_interpreter: python
    ansible_network_cli_ssh_type: libssh

  children:
    nxos:
      hosts:
        nxos101:
        nxos102:
        nxos103:
        nxos104:
      vars:
        ansible_network_os: cisco.nxos.nxos
```

and if I run with a limit for just one host:
```
(venv) x1 ➜  nav_demo ansible-navigator run site.yaml -i inventory -l nxos101 --ll debug --la false --mode stdout

PLAY [Collect interface information] *******************************************

TASK [Change an interface description] *****************************************
fatal: [nxos101]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible-pylibssh) on x1's Python /home/bthornto/github/ansible-navigator/venv/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

PLAY RECAP *********************************************************************
nxos101                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```


and we can see in the logs:

```
220128233348.196 DEBUG 'ansible_navigator.main' Running with cmdline as '['-l', 'nxos101']' (list/cli parameters)
220128233348.200 DEBUG 'ansible-runner._handle_command_wrap' command: /home/bthornto/github/ansible-navigator/venv/bin/ansible-playbook /home/bthornto/github/nav_demo/site.yaml -l nxos101 -i /home/bthornto/github/nav_demo/inventory
```

and with EE support enabled:
```
220128233927.064 DEBUG 'ansible-runner._handle_command_wrap' command: podman run --rm --tty --interactive -v /home/bthornto/github/nav_demo/:/home/bthornto/github/nav_demo/ --workdir /home/bthornto/github/nav_demo -v /home/bthornto/github/nav_demo/inventory/:/home/bthornto/github/nav_demo/inventory/ -v /run/user/1000/keyring/:/run/user/1000/keyring/ -e SSH_AUTH_SOCK=/run/user/1000/keyring/ssh -v /home/bthornto/.ssh/:/home/runner/.ssh/ -v /home/bthornto/.ssh/:/root/.ssh/ --group-add=root --ipc=host -v /tmp/ansible-navigator_mx3sua0n/artifacts/:/runner/artifacts/:Z -v /tmp/ansible-navigator_mx3sua0n/:/runner/:Z --env-file /tmp/ansible-navigator_mx3sua0n/artifacts/d26afae1-344b-45ed-bac8-00a2f9476b7b/env.list --quiet --name ansible_runner_d26afae1-344b-45ed-bac8-00a2f9476b7b quay.io/ansible/creator-ee:v0.2.0 ansible-playbook /home/bthornto/github/nav_demo/site.yaml -l nxos101 -i /home/bthornto/github/nav_demo/inventory
```
keep us posted please
