### ISSUE TITLE
ansible-navigator consumes 100% cpu when prompting

### ISSUE THREAD

**Issue by RobVerduijn** [ansible/ansible-navigator#1088]
##### ISSUE TYPE

- Bug Report

##### SUMMARY
when instructing ansible-navigator to prompt it consumes 100% cpu

##### ANSIBLE-NAVIGATOR VERSION

```bash
ansible-navigator --version
ansible-navigator 1.1.0
```

##### CONFIGURATION

no configuration has been done

##### STEPS TO REPRODUCE
to reproduce
on fedora/rhel/centos (NOT WSL)
ansible-navigator run site.yml  -m stdout --pae false --ask-vault-pass

wait for the prompt
in another shell issue the top command and check the cpu
(also note that the io is almost zero)

site.yml must be a valid playbook
secrets or vaults are optional but not required for the reproducer

site.yml example
```yaml
---
- name: reproducer
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: message
      debug:
        msg: reproducer message
```

##### EXPECTED RESULTS
while ansible-navigator waits for the password it should not consume 100% cpu

##### ACTUAL RESULTS
ansible-navigator consumes 100% cpu
