### ISSUE TITLE
Play progress reports complete while tasks are still running

### ISSUE THREAD

**Issue by branic** [ansible/ansible-navigator#1281]
##### ISSUE TYPE

- Bug Report

##### SUMMARY

During a playbook run occasionally the play `Progress` reports Complete while tasks in the play are still running

##### ANSIBLE-NAVIGATOR VERSION

```
ansible-navigator 2.1.0
```

##### CONFIGURATION

```
---
ansible-navigator:
  editor:
    command: code -g {filename}:{line_number}
    console: false
  playbook-artifact:
    enable: false
    save-as: "{playbook_dir}/run-artifacts/{playbook_name}-artifact-{time_stamp}.json"
  execution-environment:
    # image: registry.redhat.io/ansible-automation-platform/ee-minimal-rhel8:2.13
    image: localhost/aap_utilities_dev:latest
    pull:
      policy: never
    volume-mounts:
      - dest: /home/runner/.ansible/collections/ansible_collections/redhat_cop/aap_utilities
        # options: Z
        src: /home/bevans/git-repos/my_forks/ansible_collections/redhat_cop/aap_utilities
```

##### LOG FILE

No output in log file

##### STEPS TO REPRODUCE

1. Run a playbook in interactive mode.

##### EXPECTED RESULTS

Progress does not show complete until play is complete

##### ACTUAL RESULTS

Occasionally Progress is shown as complete while play is still running

##### ADDITIONAL INFORMATION

![Screenshot from 2022-08-24 16-52-54](https://user-images.githubusercontent.com/13800082/186545873-0d5f7352-5e66-4740-b123-1c9cb5e07a44.png)
