### ISSUE TITLE
Bad owner or permissions on /root/.ssh/config

### ISSUE THREAD

**Issue by watsonb** [ansible/ansible-navigator#1475]
##### ISSUE TYPE

- Bug Report

##### SUMMARY

Since upgrading beyond navigator v1.1.0, I'm seeing the error message in the title when trying to SSH to Linux hosts for fact gathering.

##### ANSIBLE-NAVIGATOR VERSION

```
ansible-navigator 1.1.0  # works
ansible-navigator 2.1.0  # error
ansible-navigator 2.2.0  # error
ansible-navigator 3.0.0  # error
```

##### CONFIGURATION

```yaml
# 1.1.0
---
ansible-navigator:
  ansible:
    config: $PWD/ansible.cfg
  ansible-runner:
    artifact-dir: $PWD/navigator_artifacts
    rotate-artifacts-count: 10
  app: welcome  # ‘collections’, ‘config’, ‘doc’, ‘images’, ‘inventory’, ‘replay’, ‘run’ or ‘welcome’
  color:
    enable: true
    osc4: true
  editor:
    command: vim +{line_number} {filename}
    console: true
  execution-environment:
    container-engine: podman
    enabled: true
    image: localhost/kiewit_ee_all:latest
    pull-policy: never
  logging:
    level: debug
    append: false
    file: $PWD/navigator.log
  mode: interactive  # interactive, stdout
  playbook-artifact:
    enable: true
    replay: $PWD/navigator_replay.json
    save-as: $PWD/navigator_replay.json
```

```yaml
# 2.1.0
---
ansible-navigator:
  ansible:
    config: $PWD/ansible.cfg
  ansible-runner:
    artifact-dir: $PWD/navigator_artifacts
    rotate-artifacts-count: 10
    timeout: 7200  # 2 hours
  app: welcome  # ‘collections’, ‘config’, ‘doc’, ‘images’, ‘inventory’, ‘replay’, ‘run’ or ‘welcome’
  color:
    enable: true
    osc4: true
  editor:
    command: vim +{line_number} {filename}
    console: true
  execution-environment:
    container-engine: podman
    enabled: true
    image: localhost/kiewit_ee_all:latest
    pull:
      policy: never
  logging:
    level: debug
    append: false
    file: $PWD/navigator.log
  mode: interactive  # interactive, stdout
  playbook-artifact:
    enable: true
    replay: $PWD/navigator_replay.json
    save-as: $PWD/navigator_replay.json
```

```yaml
# 2.2.0 && 3.0.0
---
ansible-navigator:
  ansible:
    config:
      path: $PWD/ansible.cfg
  ansible-runner:
    artifact-dir: $PWD/navigator_artifacts
    rotate-artifacts-count: 10
    timeout: 7200  # 2 hours
  app: welcome  # ‘collections’, ‘config’, ‘doc’, ‘images’, ‘inventory’, ‘replay’, ‘run’ or ‘welcome’
  color:
    enable: true
    osc4: true
  editor:
    command: vim +{line_number} {filename}
    console: true
  execution-environment:
    container-engine: podman
    enabled: true
    image: localhost/kiewit_ee_all:latest
    pull:
      policy: never
  logging:
    level: debug
    append: false
    file: $PWD/navigator.log
  mode: interactive  # interactive, stdout
  playbook-artifact:
    enable: true
    replay: $PWD/navigator_replay.json
    save-as: $PWD/navigator_replay.json
```

##### STEPS TO REPRODUCE

Execute my playbook with `ansible-navigator==1.1.0` using my custom EE and it is able to connect/gather_facts remote Linux machines.

Perform identical run with same EE using `ansible-navigator>1.1.0` and receive "Host unreachable" error with result message:
```
'Failed to connect to the host via ssh: Bad owner or permissions on /root/.ssh/config'
```

##### EXPECTED RESULTS

I expect my plays to work the same.

##### ACTUAL RESULTS

```
'Failed to connect to the host via ssh: Bad owner or permissions on /root/.ssh/config'
```

##### ADDITIONAL INFORMATION

In building my custom EE images I have tried the following progressive steps via the `append` mechanism via `ansible-builder`:

```yaml
  append: |
    #
    # Fix ownership on ssh
    #
    RUN chown -R root:root /home/runner/.ssh
    RUN chown -R root:root /root/.ssh
    RUN chmod 700 /home/runner/.ssh
    RUN chmod 700 /root/.ssh
    RUN chmod 600 /home/runner/.ssh/*
    RUN chmod 600 /root/.ssh/*
    RUN rm -f /home/runner/.ssh/config
    RUN rm -f /root/.ssh/config
```

That is to say, I've re-built and tested the resulting image after adding each line to the point the error no longer makes sense (there is no /root/.ssh/config file present in the image any longer).
