### ISSUE TITLE
SSH Agent Forwarding With MacOS and Docker Desktop

### ISSUE THREAD

**Issue by timway** [ansible/ansible-navigator#1591]
##### ISSUE TYPE

- Bug Report

##### SUMMARY

The SSH agent is not correctly mounted when using MacOS and Docker Desktop with Ansible Navigator.

##### ANSIBLE-NAVIGATOR VERSION

```
% ansible-navigator --version
ansible-navigator 3.4.0
```

##### CONFIGURATION

In one of the cases you can try to configure `ansible-navigator.yml` to mount the volume and configure the ENV variable as described in the Docker Desktop documentation.

```yml
---
ansible-navigator:
  execution-environment:
    environment-variables:
      set:
        SSH_AUTH_SOCK: /run/host-services/ssh-auth.sock
    volume-mounts:
      - src: /run/host-services/ssh-auth.sock
        dest: /run/host-services/ssh-auth.sock
```

##### LOG FILE

```bash
Warning: Issues were found while applying the settings.
   Hint: Command provided: '--mode stdout run playbook.yml --inventory hosts'

  Error: The following execution-environment.volume-mounts entry could not be parsed:  {'src': '/run/host-services/ssh-auth.sock',
         'dest': '/run/host-services/ssh-auth.sock'} (Settings file). Errors were found: Source: '/run/host-services/ssh-auth.sock'
         does not exist.
   Hint: The value of execution-environment.volume-mounts should be a list of dictionaries and valid keys are 'src', 'dest' and
         'options'.

   Note: Configuration failed, using default log file location. (/Users/abcd/efgh/ansible-navigator.log)
         Log level set to debug
   Hint: Review the hints and log file to see what went wrong.
```

##### STEPS TO REPRODUCE

Using MacOS, Python provided by MacOS, Ansible Navigator installed
Configure a target machine with SSH key based authentication using a key with a passphrase
Add the SSH key to the agent
Try to use `ansible-navigator`

##### EXPECTED RESULTS

Ideally, it detects the container runtime and automatically mounts the SSH agent into the container correctly.

##### ACTUAL RESULTS

* With no configuration it runs the playbook but is missing the credentials provided by the SSH agent
* With configuration in the `ansible-navigator.yml` to add the volume for `/run/host-services/ssh-auth.sock` it fails because the volume does not exist on the host running `ansible-navigator`
  - Should `ansible-navigator` be validating the bind mount paths or should we leave that up to the container runtime?

##### ADDITIONAL INFORMATION

https://docs.docker.com/desktop/networking/#ssh-agent-forwarding

**Comment by timway** [comment]
https://github.com/ansible/ansible-runner/pull/1293 is the PR in `ansible-runner`. A similar fix will be needed for the volume check in `ansible-navigator`. Alternatively, should the volume check be removed for `ansible-navigator` all together?

**Comment by ekartsonakis** [comment]
Hi @timway. I've posted a question here https://github.com/ansible/ansible-navigator/discussions/1621 which seems to be highly related with this issue. Could you please take a look and let me know if you have any idea?
Thank you!

**Comment by SilentRhetoric** [comment]
Also running into this issue and want to add my support for this issue getting attention.

**Comment by dbrennand** [comment]
Hi folks, I'm currently working on migrating to exclusively use Execution Environments (EE), and I hit this exact issue when trying to bind mount `/run/host-services/ssh-auth.sock` into my EE:

```yaml
---
ansible-navigator:
  execution-environment:
    environment-variables:
      set:
        SSH_AUTH_SOCK: /agent.sock
    volume-mounts:
      - src: /run/host-services/ssh-auth.sock
        dest: /agent.sock
```

I'm using OrbStack which also supports the same ['magic'](https://docs.orbstack.dev/docker/#ssh-agent-forwarding) path as Docker (e.g., `/run/host-services/ssh-auth.sock`).

I get the same error as OP due to `ansible-runner` checking whether this 'magic' path exists. However, I've worked around this by using `container-options`:

```yaml
---
ansible-navigator:
  execution-environment:
    container-engine: docker
    ...
    container-options:
      - "--volume=/run/host-services/ssh-auth.sock:/agent.sock"
    environment-variables:
      set:
        SSH_AUTH_SOCK: /agent.sock
```

CC @timway @ekartsonakis @SilentRhetoric

However, in working around that I'm now seeing that the `SSH_AUTH_SOCK` precedence is not behaving as I expected. It looks like the `SSH_AUTH_SOCK` set on the host is taking precedence over what is set in the `ansible-navigator.yml` file:

```yaml
# ...
environment-variables:
      set:
        SSH_AUTH_SOCK: /agent.sock
```

```bash
ansible-navigator exec -- /bin/bash
bash-5.2$ echo $SSH_AUTH_SOCK
/home/runner/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock
```

This makes sense though since in the `ansible-runner` [docs](https://ansible.readthedocs.io/projects/runner/en/latest/execution_environments/#ssh-symlinks) it says:

> Ansible Runner will automatically bind mount your local ssh agent UNIX-domain socket (SSH_AUTH_SOCK) into the container runtime.

But in my case, this is not the behaviour I expected, I'd expect the environment variable set in `ansible-navigator.yml` to have the highest precedence.

```
❯ uv pip list | grep ansible
ansible-builder           3.1.0
ansible-compat            25.1.4
ansible-core              2.18.4
ansible-creator           25.3.1
ansible-dev-environment   25.1.0
ansible-dev-tools         25.2.1
ansible-lint              25.1.3
ansible-navigator         25.4.0
ansible-runner            2.4.1
ansible-sign              0.1.1
pytest-ansible            25.4.0
tox-ansible               25.4.0
```
