### ISSUE TITLE
ansible-navigator run playbook.yml fails with error ansible-playbook: error: unrecognized arguments: podman

### ISSUE THREAD

**Issue by nuclear12** [ansible/ansible-navigator#1635]
##### ISSUE TYPE

- Bug Report

##### SUMMARY
Hello
ansible-navigator run is passing the podman environment as parameter to ansible-playbook
if adding the verbose option, it doesn't produce the same error

##### ANSIBLE-NAVIGATOR VERSION

```
ansible-navigator 3.5.0
```
running on AlmaLinux 9.2

##### CONFIGURATION
/root/.ansible-navigator.yml
```
---
ansible-navigator:
  ansible:
    cmdline: -ce podman
    config:
      help: false
    doc:
      help: false
      plugin:
        type: module
    inventory:
      help: false
    playbook:
      help: false
  ansible-builder:
    help: false
    workdir: /root
  ansible-runner:
    job-events: false
  app: settings
  collection-doc-cache-path: /root/.cache/ansible-navigator/collection_doc_cache.db
  color:
    enable: true
    osc4: true
  editor:
    command: vi +{line_number} {filename}
    console: true
  enable-prompts: false
  exec:
    command: /bin/bash
    shell: true
  execution-environment:
    container-engine: podman
    enabled: true
    image: registry/ansible/ansible:latest
    pull:
      policy: missing
  format: yaml
  images:
    details:
    - everything
  logging:
    append: true
    file: /root/ansible-navigator.log
    level: warning
  mode: stdout
  playbook-artifact:
    enable: true
    save-as: '{playbook_dir}/logs/{playbook_name}-artifact-{time_stamp}.json'
  settings:
    effective: true
    sample: false
    schema: json
    sources: false
  time-zone: UTC
```

ansible.cfg
```
[defaults]
inventory = inventory.yml
```

##### LOG FILE

relevant logs
when running normally
```
 cmdline_args:['/ansible/k8s/playbook.yml', '-ce', 'podman', '-i', '/ansible/inventory.yml']
2023-11-02T19:53:26.931059+00:00 DEBUG 'ansible-runner._handle_command_wrap' containerization enabled
2023-11-02T19:53:26.931555+00:00 DEBUG 'ansible-runner.wrap_args_for_containerization' container engine invocation: podman run --rm --tty --interactive -v /ansible/:/ansible/ --workdir /ansible -v /tmp/ssh-XXXXWZC0eH/:/tmp/ssh-XXXXWZC0eH/ -e SSH_AUTH_SOCK=/tmp/ssh-XXXXWZC0eH/agent.1531020 -v /root/.ssh/:/home/runner/.ssh/ -v /root/.ssh/:/root/.ssh/ --group-add=root --ipc=host -v /tmp/ansible-navigator_zbdjbbxf/artifacts/:/runner/artifacts/:Z -v /tmp/ansible-navigator_zbdjbbxf/:/runner/:Z --env-file /tmp/ansible-navigator_zbdjbbxf/artifacts/422296ac-88fe-4911-8fb2-4ef133405b6e/env.list --quiet --name ansible_runner_422296ac-88fe-4911-8fb2-4ef133405b6e --user=root registry/ansible/ansible:latest ansible-playbook /ansible/playbook.yml -ce podman -i /ansible/inventory.yml
2023-11-02T19:53:26.931612+00:00 DEBUG 'ansible-runner._handle_command_wrap' command: podman run --rm --tty --interactive -v /ansible/:/ansible/ --workdir /ansible -v /tmp/ssh-XXXXWZC0eH/:/tmp/ssh-XXXXWZC0eH/ -e SSH_AUTH_SOCK=/tmp/ssh-XXXXWZC0eH/agent.1531020 -v /root/.ssh/:/home/runner/.ssh/ -v /root/.ssh/:/root/.ssh/ --group-add=root --ipc=host -v /tmp/ansible-navigator_zbdjbbxf/artifacts/:/runner/artifacts/:Z -v /tmp/ansible-navigator_zbdjbbxf/:/runner/:Z --env-file /tmp/ansible-navigator_zbdjbbxf/artifacts/422296ac-88fe-4911-8fb2-4ef133405b6e/env.list --quiet --name ansible_runner_422296ac-88fe-4911-8fb2-4ef133405b6e --user=root registry/ansible/ansible:latest ansible-playbook /ansible/playbook.yml -ce podman -i /ansible/inventory.yml
2023-11-02T19:53:26.931955+00:00 DEBUG 'ansible_navigator.actions.run_playbook._run_runner' runner requested to start
```

when adding the -v at the end
cmdline_args:['/ansible/playbook.yml', '-v', '-i', '/ansible/inventory.yml']

##### STEPS TO REPRODUCE

ansible-navigator run playbook.yml (no other inputs)

ansible-navigator run playbook.yml -v (works correctly)

##### EXPECTED RESULTS

ansible-navigator run playbook.yml with no other variable execute correctly

##### ACTUAL RESULTS
```
usage: ansible-playbook [-h] [--version] [-v] [--private-key PRIVATE_KEY_FILE]
                        [-u REMOTE_USER] [-c CONNECTION] [-T TIMEOUT]
                        [--ssh-common-args SSH_COMMON_ARGS]
                        [--sftp-extra-args SFTP_EXTRA_ARGS]
                        [--scp-extra-args SCP_EXTRA_ARGS]
                        [--ssh-extra-args SSH_EXTRA_ARGS]
                        [-k | --connection-password-file CONNECTION_PASSWORD_FILE]
                        [--force-handlers] [--flush-cache] [-b]
                        [--become-method BECOME_METHOD]
                        [--become-user BECOME_USER]
                        [-K | --become-password-file BECOME_PASSWORD_FILE]
                        [-t TAGS] [--skip-tags SKIP_TAGS] [-C] [-D]
                        [-i INVENTORY] [--list-hosts] [-l SUBSET]
                        [-e EXTRA_VARS] [--vault-id VAULT_IDS]
                        [--ask-vault-password | --vault-password-file VAULT_PASSWORD_FILES]
                        [-f FORKS] [-M MODULE_PATH] [--syntax-check]
                        [--list-tasks] [--list-tags] [--step]
                        [--start-at-task START_AT_TASK]
                        playbook [playbook ...]
ansible-playbook: error: unrecognized arguments: podman
```

```
usage: ansible-playbook [-h] [--version] [-v] [--private-key PRIVATE_KEY_FILE]
                        [-u REMOTE_USER] [-c CONNECTION] [-T TIMEOUT]
                        [--ssh-common-args SSH_COMMON_ARGS]
                        [--sftp-extra-args SFTP_EXTRA_ARGS]
                        [--scp-extra-args SCP_EXTRA_ARGS]
                        [--ssh-extra-args SSH_EXTRA_ARGS]
                        [-k | --connection-password-file CONNECTION_PASSWORD_FILE]
                        [--force-handlers] [--flush-cache] [-b]
                        [--become-method BECOME_METHOD]
                        [--become-user BECOME_USER]
                        [-K | --become-password-file BECOME_PASSWORD_FILE]
                        [-t TAGS] [--skip-tags SKIP_TAGS] [-C] [-D]
                        [-i INVENTORY] [--list-hosts] [-l SUBSET]
                        [-e EXTRA_VARS] [--vault-id VAULT_IDS]
                        [--ask-vault-password | --vault-password-file VAULT_PASSWORD_FILES]
                        [-f FORKS] [-M MODULE_PATH] [--syntax-check]
                        [--list-tasks] [--list-tags] [--step]
                        [--start-at-task START_AT_TASK]
                        playbook [playbook ...]
```
Runs Ansible playbooks, executing the defined tasks on the targeted hosts.

##### ADDITIONAL INFORMATION

running on a custom image of almalinux with collection installed since it's inside an isolated network

```
ansible_version:
  details: ansible [core 2.15.4]
environment_variables:
  details:
    ANSIBLE_CACHE_PLUGIN: jsonfile
    ANSIBLE_CACHE_PLUGIN_CONNECTION: /runner/artifacts/dab8654f-cae1-4845-82ce-984dcad5039e/fact_cache
    ANSIBLE_CALLBACK_PLUGINS: /runner/artifacts/dab8654f-cae1-4845-82ce-984dcad5039e/callback
    ANSIBLE_HOST_KEY_CHECKING: 'False'
    ANSIBLE_RETRY_FILES_ENABLED: 'False'
    ANSIBLE_STDOUT_CALLBACK: awx_display
    ANSIBLE_UNSAFE_WRITES: '1'
    AWX_ISOLATED_DATA_DIR: /runner/artifacts/dab8654f-cae1-4845-82ce-984dcad5039e
    HOME: /root
    HOSTNAME: 85aefaa895a2
    LC_CTYPE: C.UTF-8
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    PWD: /runner/project
    SHLVL: '0'
    SSH_AUTH_SOCK: /tmp/ssh-XXXXWZC0eH/agent.1531020
    TERM: xterm
    container: podman
  os_release:
  details:
  - almalinux-mantisbt-project: AlmaLinux-9
    almalinux-mantisbt-project-version: '9.2'
    ansi-color: 0;34
    bug-report-url: 'https://bugs.almalinux.org/ '
    cpe-name: cpe:/o:almalinux:almalinux:9::baseos
    documentation-url: https://wiki.almalinux.org/
    home-url: https://almalinux.org/
    id: almalinux
    id-like: rhel centos fedora
    logo: fedora-logo-icon
    name: AlmaLinux
    platform-id: platform:el9
    pretty-name: AlmaLinux 9.2 (Turquoise Kodkod)
    redhat-support-product: AlmaLinux
    redhat-support-product-version: '9.2'
    version: 9.2 (Turquoise Kodkod)
    version-id: '9.2'
```

Thank you

**Comment by ssbarnea** [comment]
cmdargs option is intended to contain not navigator own argument but the underlying called process arguments (ansible-playbook in this case.

We will keep this bug open in order to update the documentation to be more specific.

**Comment by nuclear12** [comment]
From what i've tested, if i don't put another flag after the ansible-navigator run playbook.yml, it will fail to run with the error listed
if i add either -v or -check, the playbook executes correctly
so there seems to be a bug when the run doesn't have any arguments added that it tries to send the -ce podman as an argument to ansible-playbook which is not recognized

**Comment by shatakshiiii** [comment]
Hey @nuclear12 , In your given configuration file cmdline argument is declared as `cmdline: -ce podman`  which is causing this error. 

The cmdline option is used for passing extra parameter to the corresponding command.
For example:
```
---
ansible-navigator:
  ansible:
    cmdline: "--forks 15"
```

To specify container engine as podman, simply this should work:
```
ansible-navigator:
  execution-environment:
    container-engine: podman
```
