### ISSUE TITLE
Podman volume mount of single files are replaced by a directory mount rather than inserted correctly

### ISSUE THREAD

**Issue by hb9hnt** [ansible/ansible-navigator#1753]
##### ISSUE TYPE

- Bug Report

##### SUMMARY

Ansible navigator breaks volume mounts if you try to mount a single file rather than a directory. Specifying the following mount

```yaml
ansible-navigator:
  execution-environment:
    container-engine: podman
    volume-mounts:
      - src: /home/myuser/.ansible/linux_vault_key.txt
        dest: /var/tmp/vault-key.txt
        options: "ro"
```
leads to the following podman mount CLI option:

``` 
podman [...] -v /home/myuser/.ansible/:/var/tmp/:ro
```

##### ANSIBLE-NAVIGATOR VERSION

```
$ ansible-navigator --version
ansible-navigator 24.2.0
```

##### CONFIGURATION

```yaml
---
ansible-navigator:
  logging:
    level: debug
  ansible-lint:
    config: .ansible-lint
  color:
    enable: True
  mode: stdout
  execution-environment:
    container-engine: podman
    environment-variables:
      set:
        ANSIBLE_VAULT_PASSWORD_FILE: /var/tmp/vault-key.txt
    volume-mounts:
      - src: /home/myuser/.ansible/linux_vault_key.txt
        dest: /var/tmp/vault-key.txt
        options: "ro"
    image:  gitlab.mydomain.com:5050/project/awx
    pull:
      policy: missing
```

##### LOG FILE
The relevant part of the debug log file has been mentioned above. The mount on the podman command doesn't look as specified:

``` 
podman [...] -v /home/myuser/.ansible/:/var/tmp/:ro
```

this leads to the following errors from `ansible-playbook`:

```
No config file found; using defaults
[WARNING]: Error getting vault password file (default): The vault password file
/var/tmp/vault-key.txt was not found
ERROR! The vault password file /var/tmp/vault-key.txt was not found
```

##### STEPS TO REPRODUCE

Specify a file mount rather than a directory mount as mentioned above.

##### EXPECTED RESULTS

The podman option that should be used is as follows:

``` 
podman [...] -v /home/myuser/.ansible/linux_vault_key.txt:/var/tmp/vault-key.txt:ro
```

##### ACTUAL RESULTS

Only a directory mount is inserted in the `podman` command

``` 
podman [...] -v /home/myuser/.ansible/:/var/tmp/:ro
```
