### ISSUE TITLE
Images inspect not possible - Image introspection failed 

### ISSUE THREAD

**Issue by SchmidtJonathan1** [ansible/ansible-navigator#1795]
##### ISSUE TYPE

- Bug Report

##### SUMMARY
Try to inspect ansible EEs with ansible-navigator images

##### ANSIBLE-NAVIGATOR VERSION

```
ansible-navigator 24.3.2
```

##### CONFIGURATION
No custom settings or ansible-navigatior.yaml

##### LOG FILE
```
2024-06-12T08:09:02.121040+00:00 ERROR 'ansible_navigator.actions.images._parse' Unable to extract introspection from stdout
2024-06-12T08:09:02.121293+00:00 DEBUG 'ansible_navigator.actions.images._parse' error json loading output: 'not enough values to unpack (expected 2, got 1)'
2024-06-12T08:09:02.121381+00:00 DEBUG 'ansible_navigator.actions.images._parse' 
2024-06-12T08:09:02.121442+00:00 ERROR 'ansible_navigator.actions.images._parse' Image introspection failed (parsed), the return value was:
```

##### STEPS TO REPRODUCE
Ubuntu 22.04.4 LTS -> pip3 install ansible-dev-tools -> ansible-navigator images --ll debug -> choose creator-ee:v24.2.0  -> press 1 for General information -> got warning message (below) -> checked the ansible-navigator.log and saw the above error message

##### EXPECTED RESULTS
Show informations about the EE Image

##### ACTUAL RESULTS
Got warning message:

humph. Something went really wrong while introspecting the image.
Details have been added to the log file
[HINT] Please log an issue about this one, it shouldn't have happened

##### ADDITIONAL INFORMATION

Ubuntu 22.04.4 LTS
Python 3.10.12
ansible core 2.17.0
ansible-navigator 24.3.2
creator-ee 24.2.0
podman 3.4.4

**Comment by ssbarnea** [comment]
You included too little information on this one, we expected to see at least one more extra log line "Image introspection failed (runner)" that could give us some extra hints.

Probably you can also try to run `ansible-navigator images --ll debug --mode=stdout` to see if you still get the same error.

**Comment by SchmidtJonathan1** [comment]
This is all what i got from the Log-File, it stops with no return value..
```
2024-06-12T08:09:02.121040+00:00 ERROR 'ansible_navigator.actions.images._parse' Unable to extract introspection from stdout
2024-06-12T08:09:02.121293+00:00 DEBUG 'ansible_navigator.actions.images._parse' error json loading output: 'not enough values to unpack (expected 2, got 1)'
2024-06-12T08:09:02.121381+00:00 DEBUG 'ansible_navigator.actions.images._parse' 
2024-06-12T08:09:02.121442+00:00 ERROR 'ansible_navigator.actions.images._parse' Image introspection failed (parsed), the return value was:
```

Output from "ansible-navigator images --ll debug --mode=stdout"
```
- created: 4 months ago
  execution_environment: true
  full_name: ghcr.io/ansible/creator-ee:v24.2.0
  image_id: ddb78cf5ef52
  inspect:
    details:
      annotations: {}
      architecture: amd64
      author: ''
      comment: Created by Image Factory
      config:
        entrypoint:
        - entrypoint
        env:
        - DISTTAG=f39container
        - FGC=f39
        - container=oci
        - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - CONTAINER_NAME=creator-ee:v24.2.0
        labels:
          ansible-execution-environment: 'true'
          io.buildah.version: 1.23.1
          license: MIT
          name: fedora
          org.opencontainers.image.authors: Ansible DevTools
          org.opencontainers.image.licenses: GPL-3.0
          org.opencontainers.image.source: https://github.com/ansible/creator-ee
          org.opencontainers.image.vendor: Red Hat
          vendor: Fedora Project
          version: '39'
        user: root
        working_dir: /tmp
      created: '2024-02-08T13:57:59.985571012Z'
      digest: sha256:4ee79f6aaab2101f19a6bdd4683404fea890da79c6213c2db6fa81467fe44827
      graph_driver:
        data:
          lower_dir: /home/schmijon/.local/share/containers/storage/overlay/2745ef03f6ced705d2d81aab15b5330439afc4157cbdf15a99c7e686fe7c57fd/diff:/home/schmijon/.local/share/containers/storage/overlay/2597b012c6352cf4fe2c8ca73ad2757475515131b734a76cc1f3885f748fdd03/diff:/home/schmijon/.local/share/containers/storage/overlay/83de16645971ebf8fa6bd3c7efca641f0a812219fbb68d80d4f033dbd24f1094/diff:/home/schmijon/.local/share/containers/storage/overlay/325d742fd6256fba874c9130c9481cc023d997b82cb4f50a14f41c10c3abd50b/diff:/home/schmijon/.local/share/containers/storage/overlay/25ed50ebb94b67105b291d7f3712e2c07e7f8b7a82aeb3c96b2e2107d92554d7/diff:/home/schmijon/.local/share/containers/storage/overlay/13bc9c70b0c18296f4cd2781ac1be9bc867eeeac25fe1753e05a19398f223f87/diff:/home/schmijon/.local/share/containers/storage/overlay/034f97422b2850ac00c4c45108c1eea0182a72d90045cf2f3a2e9cb404c2bee8/diff:/home/schmijon/.local/share/containers/storage/overlay/c3f9459577e87c0829bab28b484b583f4e1eca93e6a172033982db4e3ca858e7/diff:/home/schmijon/.local/share/containers/storage/overlay/06fefc17c16aa9b791f4ed656764bb22f0185fee13636c17138d8ea3fe406c39/diff:/home/schmijon/.local/share/containers/storage/overlay/b4b19f38b817d9a741973abb6b0a8b1b94e6b1a336d777ed38cbaab7e098851b/diff:/home/schmijon/.local/share/containers/storage/overlay/1ba4077fd25de4919975e32f852fd349e37bfe0ede7276ebc4dec6a9a05f92ae/diff:/home/schmijon/.local/share/containers/storage/overlay/191babc5d0473a3e54c7726aef72f3b26f084e9fe12c2135c273e7fe9eee07ce/diff
          upper_dir: /home/schmijon/.local/share/containers/storage/overlay/5200166a6be1ec4b8269afb4b65afe2971499b76ca87ccf88afcb6ae65a50f7b/diff
          work_dir: /home/schmijon/.local/share/containers/storage/overlay/5200166a6be1ec4b8269afb4b65afe2971499b76ca87ccf88afcb6ae65a50f7b/work
        name: overlay
      history:
      - comment: Created by Image Factory
        created: '2023-11-28T07:50:22Z'
      - comment: FROM fedora-minimal
        created: '2024-02-08T13:46:06.325862097Z'
        created_by: '/bin/sh -c #(nop) LABEL org.opencontainers.image.source https://github.com/ansible/creator-ee/blob/main/base/Containerfile'
        empty_layer: true
      - created: '2024-02-08T13:46:06.358523402Z'
        created_by: '/bin/sh -c #(nop) LABEL org.opencontainers.image.authors "Ansible
          DevTools"'
        empty_layer: true
      - created: '2024-02-08T13:46:06.386025191Z'
        created_by: '/bin/sh -c #(nop) LABEL org.opencontainers.image.vendor "Red
          Hat"'
        empty_layer: true
      - created: '2024-02-08T13:46:06.413632388Z'
        created_by: '/bin/sh -c #(nop) LABEL org.opencontainers.image.licenses "GPL-3.0"'
        empty_layer: true
      - created: '2024-02-08T13:46:06.442718382Z'
        created_by: '/bin/sh -c #(nop) USER root'
        empty_layer: true
      - created: '2024-02-08T13:47:08.683781779Z'
        created_by: /bin/sh -c microdnf -y upgrade && microdnf install -y dumb-init
          gcc git-core libssh-devel podman python3 python3-bcrypt python3-cffi python3-devel
          python3-markupsafe python3-pip python3-pynacl python3-pyrsistent python3-pyyaml
          python3-ruamel-yaml python3-wheel     && microdnf clean all
      - comment: FROM creator-base
        created: '2024-02-08T13:57:18.813723225Z'
        created_by: '/bin/sh -c #(nop) ARG CONTAINER_NAME=creator-ee:v24.2.0'
        empty_layer: true
      - created: '2024-02-08T13:57:18.849878574Z'
        created_by: '/bin/sh -c #(nop) ENV CONTAINER_NAME $CONTAINER_NAME'
        empty_layer: true
      - created: '2024-02-08T13:57:18.883375488Z'
        created_by: '/bin/sh -c #(nop) LABEL org.opencontainers.image.source https://github.com/ansible/creator-ee'
        empty_layer: true
      - created: '2024-02-08T13:57:18.914009112Z'
        created_by: '/bin/sh -c #(nop) LABEL org.opencontainers.image.authors "Ansible
          DevTools"'
        empty_layer: true
      - created: '2024-02-08T13:57:18.952272627Z'
        created_by: '/bin/sh -c #(nop) LABEL org.opencontainers.image.vendor "Red
          Hat"'
        empty_layer: true
      - created: '2024-02-08T13:57:18.986712667Z'
        created_by: '/bin/sh -c #(nop) LABEL org.opencontainers.image.licenses "GPL-3.0"'
        empty_layer: true
      - created: '2024-02-08T13:57:19.023080265Z'
        created_by: '/bin/sh -c #(nop) LABEL ansible-execution-environment=true'
        empty_layer: true
      - created: '2024-02-08T13:57:19.050788222Z'
        created_by: '/bin/sh -c #(nop) USER root'
        empty_layer: true
      - created: '2024-02-08T13:57:19.111526789Z'
        created_by: '/bin/sh -c #(nop) WORKDIR /tmp'
        empty_layer: true
      - created: '2024-02-08T13:57:19.308333272Z'
        created_by: '/bin/sh -c #(nop) COPY file:61f125d139fed411b84381ace01dc0df178b741956063abb2c3e26350cea3dad
          in requirements.txt '
      - created: '2024-02-08T13:57:19.529603011Z'
        created_by: '/bin/sh -c #(nop) COPY file:76c1e3e21968ca046ce457b2c05869401af254d43ed189a3d132c84e80ac9ca8
          in requirements.yml '
      - created: '2024-02-08T13:57:19.760690558Z'
        created_by: '/bin/sh -c #(nop) COPY file:8b93e4d103bfbe033f2a0fff35e665492955c8d9791edac91b5fb3cc769aef4f
          in /usr/local/bin/devtools-publish '
      - created: '2024-02-08T13:57:19.984600663Z'
        created_by: '/bin/sh -c #(nop) COPY file:7163aef77de941b8be4726ddd45f4e769b701819375650e268e9761b65faaaaf
          in /etc/shells '
      - created: '2024-02-08T13:57:20.232261543Z'
        created_by: '/bin/sh -c #(nop) COPY file:84cf4b21208bf52e3aebf2025218585df44653566c09852896145d8b19c33178
          in /home/runner/.bashrc '
      - created: '2024-02-08T13:57:52.197039823Z'
        created_by: '|1 CONTAINER_NAME=creator-ee:v24.2.0 /bin/sh -c microdnf install
          --assumeyes ncurses && microdnf clean all && pip3 install --progress-bar=off
          -r requirements.txt && mkdir -p ~/.ansible/roles /usr/share/ansible/roles
          /etc/ansible/roles && rm -rf $(pip3 cache dir) && git config --system --add
          safe.directory / && printf "export CONTAINER_NAME=$CONTAINER_NAME\n" >>
          /home/runner/.bashrc'
      - created: '2024-02-08T13:57:54.079540684Z'
        created_by: '|1 CONTAINER_NAME=creator-ee:v24.2.0 /bin/sh -c for dir in       /home/runner       /home/runner/.ansible       /home/runner/.ansible/tmp       /runner       /home/runner       /runner/env       /runner/inventory       /runner/project       /runner/artifacts
          ;     do mkdir -m 0775 -p $dir ; chmod -R g+rwx $dir ; chgrp -R root $dir
          ; done &&     for file in       /home/runner/.ansible/galaxy_token       /etc/passwd       /etc/group
          ;     do touch $file ; chmod g+rw $file ; chgrp root $file ; done'
      - created: '2024-02-08T13:57:54.970530451Z'
        created_by: '/bin/sh -c #(nop) COPY dir:416e11aaacfbf2919b4acc662976312ed3b21a75286820d23c0a9c4e6aa14ef7
          in /usr/share/ansible/collections '
      - created: '2024-02-08T13:57:59.389559557Z'
        created_by: '|1 CONTAINER_NAME=creator-ee:v24.2.0 /bin/sh -c set -ex && ansible
          --version && ansible-lint --version && ansible-runner --version && molecule
          --version && molecule drivers && podman --version && python3 --version &&
          git --version && ansible-galaxy role list && ansible-galaxy collection list
          && rpm -qa && uname -a'
      - created: '2024-02-08T13:57:59.617500538Z'
        created_by: '/bin/sh -c #(nop) ADD file:4b6d9f5b0aa082bed0e707a401804b271d21a39395845c836edba2626f3d1634
          in /bin/entrypoint '
      - created: '2024-02-08T13:57:59.897389286Z'
        created_by: '|1 CONTAINER_NAME=creator-ee:v24.2.0 /bin/sh -c chmod +x /bin/entrypoint'
      - created: '2024-02-08T13:57:59.986266298Z'
        created_by: '/bin/sh -c #(nop) ENTRYPOINT ["entrypoint"]'
        empty_layer: true
      id: ddb78cf5ef525faf46344166172f3ddba05e680ff28341d41168a93d7c51fd55
      labels:
        ansible-execution-environment: 'true'
        io.buildah.version: 1.23.1
        license: MIT
        name: fedora
        org.opencontainers.image.authors: Ansible DevTools
        org.opencontainers.image.licenses: GPL-3.0
        org.opencontainers.image.source: https://github.com/ansible/creator-ee
        org.opencontainers.image.vendor: Red Hat
        vendor: Fedora Project
        version: '39'
      manifest_type: application/vnd.oci.image.manifest.v1+json
      names_history:
      - ghcr.io/ansible/creator-ee:v24.2.0
      os: linux
      parent: ''
      repo_digests:
      - ghcr.io/ansible/creator-ee@sha256:4ee79f6aaab2101f19a6bdd4683404fea890da79c6213c2db6fa81467fe44827
      - ghcr.io/ansible/creator-ee@sha256:ecaa4029b96daa14a2db8103d5df831cfc35b3c05336f00548ed4196e01689b9
      repo_tags:
      - ghcr.io/ansible/creator-ee:v24.2.0
      root_fs:
        layers:
        - sha256:191babc5d0473a3e54c7726aef72f3b26f084e9fe12c2135c273e7fe9eee07ce
        - sha256:2e7f0cfca74a1f12fe334d2cf56a071f06150f874a3eeb9dbb30b80d0a1b93d8
        - sha256:c333fba26aaebd3e57b1b037fbd5732fb962cfe1e7f972b0ba867b613130f469
        - sha256:5d867eb93072e6fe18e23939e32ec2fb24ad5902f3296bf13425fe84dfba28f7
        - sha256:663e7172945398168a41175f3b8d6c41992f87de259b4e27fbc5d61902bf9a40
        - sha256:f85ae45acc18746c5441bce282855505c2d80eec1cfbdcc20f033a0b7ba0ce53
        - sha256:5572cefe6bebf9a44ebed05bb8412cc5d9eb2c9fa760763d49574e61464393af
        - sha256:a443165935c8409689e5646e621ab6a1354579b53c5ec2b83ba61b1b9ebcdc86
        - sha256:53f3b44971633d9efd08ce0f2f35779f8a7c31e1937d6987e1d9534f4f9b4f86
        - sha256:14cdffa6e2c6ac7b7fedeaeee86fb75b7255f60f29c7f01b6c08b25f969b7f06
        - sha256:18c877caa42e9d9afe4f3cd33523f1d1c68e59a560a00e90e9070b117c9d9b22
        - sha256:7b5efca30fb3e7876a131a9bdd6b5b7e7d47cde9eaebb2955b0b48008ae68c5f
        - sha256:9d4799330355bb5c90f2b82de6f4a4315cf8d9af7e0158eb39bf1b0c3259748f
        type: layers
      size: 887509897
      user: root
      version: ''
      virtual_size: 887509897
    errors: ''
  name: creator-ee
  name_tag: creator-ee:v24.2.0 (primary)
  repository: ghcr.io/ansible/creator-ee
  size: 888 MB
  tag: v24.2.0
```
  
  
  Do you need more informations?

**Comment by SchmidtJonathan1** [comment]
Hello @ssbarnea, are thees enough informations written in my last post?

**Comment by SchmidtJonathan1** [comment]
Hello @ssbarnea @shatakshiiii , are thees enough informations written in my last post?

**Comment by stephendorman** [comment]
I am also experiencing this issue

Version: `ansible-navigator 24.8.0`
Cmd: `ansible-navigator images --ll debug` (then select image)
Error:
```
2024-08-14T18:24:17.615294+00:00 ERROR 'ansible_navigator.actions.images._parse' Unable to extract introspection from stdout
...
ValueError: not enough values to unpack (expected 2, got 1)
2024-08-14T18:24:17.616325+00:00 DEBUG 'ansible_navigator.actions.images._parse' error json loading output: 'not enough values to unpack (expected 2, got 1)'
```

**Comment by stephendorman** [comment]
fwiw the last time this worked was `v24.2.0`. Haven't dug into any more than that... I've been using that pinned version.

**Comment by falon** [comment]
> fwiw the last time this worked was `v24.2.0`. Haven't dug into any more than that... I've been using that pinned version.

I have this problem, which I can resolve as above written.

Really, in a custom EE I resolved this problem in another way. The error was:

```
2025-02-05T14:45:46.776781+01:00 ERROR 'ansible_navigator.actions.images._parse' Image introspection failed (parsed), the return value was: Traceback (most recent call last):
  File "/root/.cache/ansible-navigator/image_introspect.py", line 16, in <module>
    from typing import TypeAlias
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/lib64/python3.9/typing.py)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/ansible_navigator/actions/images.py", line 537, in _parse
    _warnings, json_str = output.split("{", 1)
    ^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

So it seems that ansible-navigator (`25.1.0` too) doesn't use  the
```
dependencies:
  python_interpreter:
    package_system: python3.12
    python_path: /usr/bin/python3.12
```
at all. So I add to the **execution.environment.yml**:
```
  prepend_final:
    - RUN update-alternatives --install /usr/bin/python3 python /usr/bin/python3.12 20
```
and now it works! But I have to change system python which is not good, I think.


If I change the entrypoint from default to systemd (I love to run tests in systemd) I can't read collection and package through navigator yet. It seems that ansible-navigator can't parse multiple line that systemd outputs.
