### ISSUE TITLE
Can not start ansible-navigator container in podman on mac os

### ISSUE THREAD

**Issue by dkoci** [ansible/ansible-navigator#1814]
##### ISSUE TYPE

- Bug Report

##### SUMMARY

Hi.
I followed the [Installing ansible-navigator (macos) instructions](https://ansible.readthedocs.io/projects/navigator/installation/#install-ansible-navigator-macos). When i try to run playbook with ansible-navigator, I get

`Error: preparing container cdff01dfcab0d78e9fbaef67bf4a93cb5e40624ce01ed0adbe06d64fd01e8e27 for attach: lsetxattr /var/folders/rh/x8nmgc4x1rl9tsjy4phwv5hh0000gn/T/ansible-navigator_6v8bx7fr/artifacts: operation not supported
Please review the log for errors.`

##### ANSIBLE-NAVIGATOR VERSION

```
24.6.0
```

##### CONFIGURATION

```yaml
ansible-navigator:
  execution-environment:
    image: quay.io/ansible/awx-ee:latest
    pull:
      policy: missing
    environment-variables:
      set:
        ANSIBLE_CONFIG: ansible.cfg
  mode: stdout
  playbook-artifact:
    enable: false
```

##### STEPS TO REPRODUCE

`ansible-navigator run playbook.yml`

##### EXPECTED RESULTS

Playbok should execute

##### ACTUAL RESULTS

Get error

`Error: preparing container cdff01dfcab0d78e9fbaef67bf4a93cb5e40624ce01ed0adbe06d64fd01e8e27 for attach: lsetxattr /var/folders/rh/x8nmgc4x1rl9tsjy4phwv5hh0000gn/T/ansible-navigator_6v8bx7fr/artifacts: operation not supported
Please review the log for errors.`
