### ISSUE TITLE
[settings] Check cmdline from file to runner

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-navigator#381]
It's a string in the file, need to ensure it gets split

re #372

**Comment by s-hertel** [comment]
Looks like there's no string splitting when there's no playbook prompting.

Reproducer:
```
# navigator_settings.yml
ansible-navigator:
  ansible:
    cmdline: "--forks 15"
    playbook: test_playbook.yml
```

```
# test_playbook.yml
- hosts: localhost
  gather_facts: no
  tasks:
  - assert:
      that: "ansible_forks == 15"
```

`$ ANSIBLE_NAVIGATOR_CONFIG=./navigator_settings.yml ansible-navigator --ee false run`
