### ISSUE TITLE
:images main page should indicate whether execution environment use is enabled 

### ISSUE THREAD

**Issue by yagomarques** [ansible/ansible-navigator#415]
On this page there is not the information about the EE enabled.

there is an information about the **main EE** used on the `ansible-navigator config` but if this EE is unabled we don't know.

![image](https://user-images.githubusercontent.com/18562328/120361179-f17e1680-c2df-11eb-9f5c-3384d2214315.png)

config example:
```
ansible-navigator:
#   app: run
#   collection-doc-cache-path: /tmp/cache.db
#   cmdline: "--forks 15"
#   editor:
#     command: vim_from_setting
#     console: False
#   documentation:
#     plugin:
#       name: shell
#       type: become
  execution-environment:
    image: "quay.io/ansible/awx-ee:devel"
    enabled: False

  log:
    level: debug
```
