### ISSUE TITLE
Image introspection failed (WSL2 Ubuntu 20.04)

### ISSUE THREAD

**Issue by watsonb** [ansible/ansible-navigator#610]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I'm trying to use `ansible-navigator` on Ubuntu 20.04 via WSL 2 with `podman`.  I followed podman install instructions here: https://www.redhat.com/sysadmin/podman-windows-wsl2

Yes, I recognize WSL2 support may be a stretch goal, but it is one I'm working toward nonetheless.

Using my `ansible-navigator.yml` config, when I run `ansible-navigator`, the specified EE image is pulled from our Azure Container Registry and I am greeted by the "welcome" page.  When I list images, I see my image.  When I try to inspect the version of Ansible and collections contained in the image, I get an error message from `ansible-navigator` stating that it failed to introspect the image and that this is probably a bug that I should report.

##### ANSIBLE-NAVIGATOR VERSION

```
ansible-navigator 1.1.0
```

Other pertinent environment information:
```bash
wsl --status
Default Distribution: Ubuntu-20.04
Default Version: 2

Windows Subsystem for Linux was last updated on 10/14/2021
WSL automatic updates are on.

Kernel version: 5.10.60.1

wsl --list --verbose
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         2
```

Ubuntu 20.04 is a completely fresh (apt update) install.  Inside Ubuntu 20.04:

```bash
$ ansible-navigator --version
ansible-navigator 1.1.0

$ podman --version
podman version 3.3.1

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

$ python --version
Python 3.8.10

$ pip --version
pip 21.3.1 from /home/ben/venv_ansible_navigator/lib/python3.8/site-packages/pip (python 3.8)
```

##### CONFIGURATION

```yml
---
ansible-navigator:
  ansible:
    config: $PWD/ansible.cfg

  ansible-runner:
    artifact-dir: $PWD/navigator_artifacts
    rotate-artifacts-count: 10
    timeout: 300

  app: welcome  # ‘collections’, ‘config’, ‘doc’, ‘images’, ‘inventory’, ‘replay’, ‘run’ or ‘welcome’

  collection-doc-cache-path: $PWD/cache.db

  color:
    enable: True
    osc4: True

  editor:
    command: vim +{line_number} {filename}
    console: True

  execution-environment:
    container-engine: podman
    enabled: true
    image: cregprod01scusdco.azurecr.io/kiewit/kiewit_ee_all:latest
    pull-policy: tag

  logging:
    level: warning
    append: False
    file: $PWD/navigator.log

  mode: interactive  # interactive, stdout

  playbook-artifact:
    enable: True
    replay: $PWD/navigator_replay.json
    save-as: $PWD/navigator_replay.json

```

##### LOG FILE

```
211116143650.609 WARNING 'ansible_navigator.image_manager.puller._log_message' Image inspection failed, image assumed to be corrupted or missing
211116144641.748 ERROR 'ansible_navigator.actions.images._parse' Unable to extract introspection from stdout
211116144641.748 ERROR 'ansible_navigator.actions.images._introspect_image' Image introspection failed (parsed), the return value was: Error: statfs /dev/mqueue: no such file or directory
```

##### STEPS TO REPRODUCE

```bash
podman login -u <username> -p <password> <registry>
ansible-navigator
```

##### EXPECTED RESULTS

expect to be able to use the TUI to introspect image(s) and `run` playbooks

##### ACTUAL RESULTS

```bash
  WARNING
                                                                   ─────────────────────────────────────────────────────────────────────
                                                                   humph. Something went really wrong while introspecting the image.
                                                                   Details have been added to the log file
                                                                   [HINT] Please log an issue about this one, it shouldn't have happened
                                                                   ─────────────────────────────────────────────────────────────────────
```

##### ADDITIONAL INFORMATION

This all seems to stem from `/dev/mqueue` not available in a WSL2 Ubuntu environment.
