### ISSUE TITLE
Can't mount custom volume with ansible collections to execution environment

### ISSUE THREAD

**Issue by jwerak** [ansible/ansible-navigator#764]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I am not able to add ansible collections to to execution environment when running ansible-navigator commands.

##### ANSIBLE-NAVIGATOR VERSION

```
ansible-navigator 1.1.0
```

Also I am on Fedora 34 and using podman.

##### CONFIGURATION

```yaml
---
ansible-navigator:
  execution-environment:
    image: registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8:1.0.0-30
    environment-variables:
      set:
        ANSIBLE_COLLECTIONS_PATHS: /home/jveverka/git/jwerak/ansible
    volume-mounts:
      - src: "/home/jveverka/git/jwerak/ansible"
        dest: "/home/jveverka/git/jwerak/ansible"
        label: "Z"
  logging:
    level: critical
    file: /tmp/log.txt
```

##### LOG FILE

Debug log output: https://raw.githubusercontent.com/jwerak/collection-test/master/log.txt

##### STEPS TO REPRODUCE

- Download the collection from https://github.com/jwerak/collection-test 
- Login to container registry registry.redhat.io
  - e.g. `podman login registry.redhat.io`
- Update ansible-navigator.yml to have base path relevant for your system
- List collections
  - `ansible-navigator collections --log-leve debug`

##### EXPECTED RESULTS

The command output displays the collections under my ansible collections base path.

##### ACTUAL RESULTS

No collections found.

##### ADDITIONAL INFORMATION

The collection for testing purposes is here: https://github.com/jwerak/collection-test

**Comment by relrod** [comment]
I'm unable to reproduce this.

If I create `/tmp/foo/ansible_collections` and clone your repo to `/tmp/foo/ansible_collections/jwerak/collection_test/`
... and have this config under `ansible-navigator.execution-environment`:

```yaml
    volume-mounts:
      - { src: /tmp/foo, dest: /tmp/foo, label: Z }
    environment-variables:
      set:
        ANSIBLE_COLLECTIONS_PATHS: /tmp/foo
```

... `ansible-navigator collections` shows it for me.

Can you confirm you're still seeing an issue? If you are, then (assuming you have ansible installed locally too), can you try setting `ANSIBLE_COLLECTIONS_PATHS` locally and see if `ansible-galaxy collection list` picks it up?
