### ISSUE TITLE
how to pass limit to ansible-navigator run

### ISSUE THREAD

**Issue by DE110283** [ansible/ansible-navigator#827]
I can't find any information about how to pass a limit for example to a given host or group when executing playbooks using ansible-navigator run.
If this feature is not available I would like to raise a feature request to add a limit argument, like for ansible-playbook:

`ansible-navigator run <playbook> -l <host|group>`

**Comment by cidrblock** [comment]
@DE110283 Thanks for the question...

ansible-navigator should pass through any unrecognized by it to the underlying call to ansible-playbook.

So it _should_ just "work" :)

It's buried pretty deep in the help, but if you `ansible-navigator run --help``` you'll see this.


```
Note: 'ansible-navigator run' additionally supports the same parameters as the 'ansible-playbook' command. For more information about these, try 'ansible-navigator run --help-playbook --mode stdout'
```

Try it out and let me know, I'm shutting down for the day but can look next week.

**Comment by cidrblock** [comment]
yeah, this works fine.... here's my inventory

```
all:
  vars:
    ansible_user: admin
    ansible_password: password
    ansible_become_pass: password
    ansible_become: True
    ansible_become_method: enable
    ansible_connection: ansible.netcommon.network_cli
    ansible_python_interpreter: python
    ansible_network_cli_ssh_type: libssh

  children:
    nxos:
      hosts:
        nxos101:
        nxos102:
        nxos103:
        nxos104:
      vars:
        ansible_network_os: cisco.nxos.nxos
```

and if I run with a limit for just one host:
```
(venv) x1 ➜  nav_demo ansible-navigator run site.yaml -i inventory -l nxos101 --ll debug --la false --mode stdout

PLAY [Collect interface information] *******************************************

TASK [Change an interface description] *****************************************
fatal: [nxos101]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible-pylibssh) on x1's Python /home/bthornto/github/ansible-navigator/venv/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

PLAY RECAP *********************************************************************
nxos101                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```

keep us posted please
